In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
data = pd.read_csv('Churn_Modelling.csv')

In [3]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [4]:
data.drop(['RowNumber','CustomerId','Surname'],axis=1,inplace=True)

In [5]:
data['Gender'] = data['Gender'].map({'Female':0,'Male':1})

In [6]:
data.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France       0   42       2       0.00              1   
1          608     Spain       0   41       1   83807.86              1   
2          502    France       0   42       8  159660.80              3   
3          699    France       0   39       1       0.00              2   
4          850     Spain       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  Exited  
0          1               1        101348.88       1  
1          0               1        112542.58       0  
2          1               0        113931.57       1  
3          0               0         93826.63       0  
4          1               1         79084.10       0

In [7]:
data = pd.get_dummies(data,drop_first=True)

In [8]:
data.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Exited  Geography_Germany  Geography_Spain  
0               1        101348.88       1                  0                0  
1               1        112542.58       0                  0                1  
2               0        113931.57       1                  0                0  
3               0         93826.63       0                  0                0  
4               1         79084.10       0                  0                1

In [9]:
y = data['Exited'].values

In [10]:
y[:3]

array([1, 0, 1], dtype=int64)

In [11]:
X = data.drop('Exited',axis=1).values

In [12]:
X[:3]

array([[6.1900000e+02, 0.0000000e+00, 4.2000000e+01, 2.0000000e+00,
        0.0000000e+00, 1.0000000e+00, 1.0000000e+00, 1.0000000e+00,
        1.0134888e+05, 0.0000000e+00, 0.0000000e+00],
       [6.0800000e+02, 0.0000000e+00, 4.1000000e+01, 1.0000000e+00,
        8.3807860e+04, 1.0000000e+00, 0.0000000e+00, 1.0000000e+00,
        1.1254258e+05, 0.0000000e+00, 1.0000000e+00],
       [5.0200000e+02, 0.0000000e+00, 4.2000000e+01, 8.0000000e+00,
        1.5966080e+05, 3.0000000e+00, 1.0000000e+00, 0.0000000e+00,
        1.1393157e+05, 0.0000000e+00, 0.0000000e+00]])

In [13]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.25,stratify=y,random_state=101)

In [14]:
X_train.shape

(7500, 11)

In [15]:
X_test.shape

(2500, 11)

In [16]:
from sklearn.preprocessing import StandardScaler
scale_X = StandardScaler()
X_train = scale_X.fit_transform(X_train)
X_test = scale_X.transform(X_test)

In [17]:
X_train[:4]

array([[ 1.86932689, -1.0794105 ,  0.49029212,  1.73983724, -1.22309334,
        -0.90904157, -1.55412372,  0.97134375, -0.91598568, -0.57878723,
         1.75072575],
       [-1.2790784 , -1.0794105 , -0.85049006, -1.73002909,  1.30818554,
         0.80139791,  0.64344941,  0.97134375,  0.00626315,  1.72775062,
        -0.57119169],
       [ 0.40830221, -1.0794105 ,  1.54376383, -0.34208256, -1.22309334,
         0.80139791,  0.64344941,  0.97134375, -0.72942436, -0.57878723,
         1.75072575],
       [-1.13503372,  0.92643161, -0.08432881,  0.35189071, -1.22309334,
        -0.90904157,  0.64344941,  0.97134375,  0.91517343, -0.57878723,
         1.75072575]])

In [18]:
import keras    

Using TensorFlow backend.


In [19]:
from keras.models import Sequential
from keras.layers import Dense

In [20]:
model = Sequential()

In [21]:
model.add(Dense(6,activation='relu',input_shape=(11,)))

Instructions for updating:
Colocations handled automatically by placer.


In [22]:
model.add(Dense(6,activation='relu'))

In [23]:
model.add(Dense(1,activation='sigmoid'))

In [24]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [25]:
model.fit(X_train,y_train,batch_size=20,epochs=25)

Instructions for updating:
Use tf.cast instead.
Epoch 1/25
7500/7500 [==============================] - 6s 786us/step - loss: 0.5282 - acc: 0.7781
Epoch 2/25
7500/7500 [==============================] - 1s 140us/step - loss: 0.4524 - acc: 0.7963
Epoch 3/25
7500/7500 [==============================] - 1s 143us/step - loss: 0.4318 - acc: 0.7996
Epoch 4/25
7500/7500 [==============================] - 1s 138us/step - loss: 0.4190 - acc: 0.8081
Epoch 5/25
7500/7500 [==============================] - 1s 147us/step - loss: 0.4088 - acc: 0.8161
Epoch 6/25
7500/7500 [==============================] - 1s 137us/step - loss: 0.4010 - acc: 0.8231
Epoch 7/25
7500/7500 [==============================] - 1s 140us/step - loss: 0.3950 - acc: 0.8299
Epoch 8/25
7500/7500 [==============================] - 1s 137us/step - loss: 0.3903 - acc: 0.8355
Epoch 9/25
7500/7500 [==============================] - 1s 141us/step - loss: 0.3860 - acc: 0.8389
Epoch 10/25
7500/7500 [==============================] - 1s 1

In [30]:
y_pred = model.predict(X_test)

In [32]:
y_pred = y_pred>0.5 

In [33]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)

array([[1938,   53],
       [ 303,  206]], dtype=int64)

In [34]:
accuracy_score(y_test,y_pred)

0.8576

In [35]:
from sklearn.ensemble import VotingClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC

In [36]:
lin_model = LogisticRegression()
knn_model = KNeighborsClassifier()
scv = SVC()

In [37]:
classifiers = [('LogisticRegression',lin_model),('KNeighborsClassifier',knn_model),('SVC',scv)]

In [39]:
for name,model in classifiers:
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    print(name,accuracy_score(y_test,y_pred))

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


LogisticRegression 0.8068
KNeighborsClassifier 0.8204
SVC 0.8484


In [40]:
vc_model = VotingClassifier(estimators=classifiers)

In [41]:
vc_model.fit(X_train,y_train)

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


VotingClassifier(estimators=[('LogisticRegression',
                              LogisticRegression(C=1.0, class_weight=None,
                                                 dual=False, fit_intercept=True,
                                                 intercept_scaling=1,
                                                 l1_ratio=None, max_iter=100,
                                                 multi_class='warn',
                                                 n_jobs=None, penalty='l2',
                                                 random_state=None,
                                                 solver='warn', tol=0.0001,
                                                 verbose=0, warm_start=False)),
                             ('KNeighborsClassifier',
                              KNeighborsClassifier(algorithm='auto',
                                                   l...
                                                   metric_params=None,
                         

In [42]:
y_pred = vc_model.predict(X_test)

In [43]:
accuracy_score(y_test,y_pred)

0.8424

In [44]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV

In [45]:
dt = DecisionTreeClassifier()
myset = {'criterion':['gini','entropy'],'min_samples_split':[2,5,10,15],'min_samples_leaf':[0.1,0.15,0.20]}

In [47]:
gs = GridSearchCV(dt,param_grid=myset,scoring='accuracy')

In [48]:
gs.fit(X_train,y_train)

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:1978: FutureWarning: The default value of cv will change from 3 to 5 in version 0.22. Specify it explicitly to silence this warning.
  warnings.warn(CV_WARNING, FutureWarning)


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=DecisionTreeClassifier(class_weight=None,
                                              criterion='gini', max_depth=None,
                                              max_features=None,
                                              max_leaf_nodes=None,
                                              min_impurity_decrease=0.0,
                                              min_impurity_split=None,
                                              min_samples_leaf=1,
                                              min_samples_split=2,
                                              min_weight_fraction_leaf=0.0,
                                              presort=False, random_state=None,
                                              splitter='best'),
             iid='warn', n_jobs=None,
             param_grid={'criterion': ['gini', 'entropy'],
                         'min_samples_leaf': [0.1, 0.15, 0.2],
         

In [49]:
gs.best_params_

{'criterion': 'gini', 'min_samples_leaf': 0.1, 'min_samples_split': 2}

In [50]:
gs.best_score_

0.8190666666666667

In [54]:
dt_new = DecisionTreeClassifier(min_samples_leaf=0.1)

In [55]:
dt_new.fit(X_train,y_train)

DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=None,
                       max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=0.1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort=False,
                       random_state=None, splitter='best')

In [56]:
y_pred = dt_new.predict(X_test)

In [57]:
accuracy_score(y_test,y_pred)

0.8052

In [60]:
import warnings
warnings.filterwarnings('ignore')
from sklearn.model_selection import cross_val_score
cross_val_score(vc_model,X_train,y_train,cv=10,scoring='accuracy').mean()

0.8445337559711217