In [1]:
#Importing Libraries

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
#Reading the Dataset
data = pd.read_csv('Data.csv')

In [3]:
data.head()

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 400.0+ bytes


In [5]:
data.columns

Index(['Country', 'Age', 'Salary', 'Purchased'], dtype='object')

In [6]:
#Independent Variable 
# Country,Age,Salary

#Dependent Variable 
#Purchased

In [7]:
#Taking Control over missing values

#Their are two ways to solve missing data issue
# 1. From library named as Imputer
# 2. fillna method(I love this one)

#Imputer way

# from sklearn.preprocessing import Imputer
# imputer = Imputer(missing_values='NaN',strategy='mean',axis=0) (For columns axis=0 and for rows axis=1 )
# imputer = imputer.fit(X[:,1:3])
# X[:,1:3]  = imputer.transform(X[:,1:3])
#Note this method must be done after splitting data into X and y

In [8]:
# We'll clean data through fillna method
data['Age'] = data['Age'].fillna(np.mean(data['Age']))
data['Salary'] = data['Salary'].fillna(np.mean(data['Salary']))

In [10]:
#Dividing the dataset into X and y
X = data.iloc[:,:-1].values # All the columns except last one i.e all the independent columns
y = data.iloc[:,3].values # Last Column i.e the dependent colunn

In [11]:
#As Country column is categorical,we need to change it into numeric

#Again their are two methods to do that
#apply function(Not Advertised ,as we need dummy variables)
# From library LabelEncoder and OneHotEncoder

In [12]:
# #Using LabelEncoder and OneHotEncoder for categorical data

from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder_X = LabelEncoder()
X[:,0] = labelencoder_X.fit_transform(X[:,0])
onehotencoder = OneHotEncoder(categorical_features=[0])
X = onehotencoder.fit_transform(X).toarray()
labelencoder_y = LabelEncoder()
y = labelencoder_y.fit_transform(y)

In [13]:
from sklearn.cross_validation import train_test_split

C:\Users\Acer\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [14]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=0)

In [15]:
X_train

array([[0.00000000e+00, 1.00000000e+00, 0.00000000e+00, 4.00000000e+01,
        6.37777778e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.70000000e+01,
        6.70000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 2.70000000e+01,
        4.80000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.87777778e+01,
        5.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.80000000e+01,
        7.90000000e+04],
       [0.00000000e+00, 0.00000000e+00, 1.00000000e+00, 3.80000000e+01,
        6.10000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 4.40000000e+01,
        7.20000000e+04],
       [1.00000000e+00, 0.00000000e+00, 0.00000000e+00, 3.50000000e+01,
        5.80000000e+04]])

In [16]:
X_test

array([[0.0e+00, 1.0e+00, 0.0e+00, 3.0e+01, 5.4e+04],
       [0.0e+00, 1.0e+00, 0.0e+00, 5.0e+01, 8.3e+04]])

In [17]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1], dtype=int64)

In [18]:
y_test

array([0, 0], dtype=int64)

In [ ]:
# Data Preproceesing is done